batch_size:        500
feat_dropout:      0.3
n_tree:            3
tree_depth:        10
n_class:           10
tree_feature_rate: 0.5
lr:                0.1
gpuid:             0
epochs:            10
report_every:      10
